#!/bin/env bash
# +-- created by: achmur -------------- time4Linux ------------------------+ #
# |     __  __ __  __    _                           __           .--.     | #
# |    / /_/ // / / /   (_)___  __  ___  __   ____  / /          |ö_ö |    | #
# |   / __/ // /_/ /   / / __ \/ / / / |/_/  / __ \/ /           |\ü/ |    | #
# |  / /_/__  __/ /___/ / / / / /_/ />  < _ / /_/ / /           //   \ \   | #
# |  \__/  /_/ /_____/_/_/ /_/\__,_/_/|_/(_) .___/_/           (|     | )  | #
# |                                       /_/                 /'\_   _/`\\ | #
# |  Version     : 1.0                         2023-01-15     \___)=(___// | #
# +------------------------------------------ 2023-03-01 ------------------+ #
# |  Description : script template                                         | # 
# |                   having fun with scripting                            | #
# |  USED        - function
# |              - 
# +------------------------------------------------------------------------+ #
. my_colors

# |----------------  INFORMATION about the script  ------------------------| 
help(){
	echo -e "Script requirements:\n"
	echo -e "       $BGreen$(basename $0)$Color_Off <file_name>   
           - creates a script in working directory" 
	echo -e "       $BGreen$(basename $0)$Color_Off [$Green-w$Color_Off/$Green-s$Color_Off/$Green-t$Color_Off <file_name>]\n"
	echo -e "-s creates a script file in $Green$HOME$Color_Off/t4Linux/home_lab/scripts/testing"
	echo -e "-t creates a script file in $Green$HOME$Color_Off/tmp"
	echo -e "-l lists all the scripts in $Green$HOME$Color_Off/home_lab/scripts"
}
# |----------------  New script content  ----------------------------------| 
content(){
	touch $new_script
	cat > $new_script<< EOF
#!/bin/env bash
# +-- created by: achmur -------------- time4Linux ------------------------+ #
# |     __  __ __  __    _                           __           .--.     | #
# |    / /_/ // / / /   (_)___  __  ___  __   ____  / /          |ö_ö |    | #
# |   / __/ // /_/ /   / / __ \/ / / / |/_/  / __ \/ /           |\ü/ |    | #
# |  / /_/__  __/ /___/ / / / / /_/ />  < _ / /_/ / /           //   \ \   | #
# |  \__/  /_/ /_____/_/_/ /_/\__,_/_/|_/(_) .___/_/           (|     | )  | #
# |                                       /_/                 /'\_   _/\`\\\ | #
# |  Version     : 0.1                         $(date +%Y-%m-%d)     \___)=(___// | #
# +------------------------------------------ $(date +%Y-%m-%d) ------------------+ #
# |  Description :                                                         | # 
# |                                                                        | #
# +------------------------------------------------------------------------+ #
. my_colors
# |------------------------                      --------------------------| #
EOF
}
# |----------------  Man pages  -------------------------------------------| #
scr_man(){
echo -e "
$BGreen NAME$Color_OFF
	$IGreen $(basename $0)$Color_Off - script template\n
$BGreen SYNOPSIS
	$IGreen $(basename $0)$Color_Off [flag] [file_name]\n
$BGreen OPTIONS\n
	$IGreen-l$Color_Off
	lists all scripts\n
	$IGreen-w$Color_Off <file_name>
	creates a script file in workin directory - $Green$(pwd)$Color_Off\n
	$IGreen-s$Color_Off <file_name>\n
	creates a script file in $Green$HOME/home_lab/scripts$Color_Off
	$IGreen-h$Color_Off\n
	displays this help file
"
}
# |----------------  Checking script's validity ---------------------------| 
# # checking for arguments
if [ ${#} -eq 0 ]; then
 	help
# # checking for flags
elif [[ $1 == -? ]]; then
# # getopts
while getopts 'h:s:lm:t:' OPTION; do
	case "$OPTION" in
		h)
			help
			;;
		s)
			svalue="$OPTARG"
			new_script=$HOME/t4Linux/home_lab/scripts/testing/$OPTARG.sh
			content
      chmod +x $new_script
			${EDITOR} $new_script
			;;
		l)
      echo -e "t4Linux/home_lab/scripts:\n"
      if ! command -v exa &>/dev/null; then 
        ls -gh --time-style=+%Y-%m-%d $HOME/t4Linux/home_lab/scripts/ | awk '{ print $4 " " $5  }'
      else
        exa -lg --group-directories-first --icons --color-scale --time-style=long-iso $HOME/dotfiles/bin  | awk '{ print $5 " " $7 " " $8 }'
      fi
			;;
		t)
			svalue="$OPTARG"
			new_script=$HOME/tmp/$OPTARG.sh
			content
      chmod +x $new_script
			${EDITOR} $new_script
			;;
		m)
			scr_man | less
			;;
		*)
			help
			echo "gdzie jest *"
			;;
	esac
done
# #  NEW SCRIPT in pwd
else
  touch $1.sh
  new_script=$(pwd)/$1.sh
  content
  chmod +x $new_script
  ${EDITOR} $new_script
fi
